const fs = require('fs');
let content = fs.readFileSync('./taoyuan-main/src/views/game/FarmView.vue', 'utf8');

// Replace standard strings in script block
const replacements = [
  // 1145
  ["return '点击下方「一键操作」→「一键开垦」来开垦荒地，或直接点击地块逐一操作。'", "return i18n.global.locale.value === 'vi' ? 'Nhấp vào 「Thao tác nhanh」→「Khai khẩn hàng loạt」bên dưới để khai khẩn, hoặc nhấp từng ô.' : '点击下方「一键操作」→「一键开垦」来开垦荒地，或直接点击地块逐一操作。'"],
  ["return '已开垦的地块可以种植作物。使用「一键种植」可批量播种背包中的种子。'", "return i18n.global.locale.value === 'vi' ? 'Khung đất đã khai khẩn có thể trồng cây. Dùng 「Gieo hạt hàng loạt」 để gieo nhiều hạt giống.' : '已开垦的地块可以种植作物。使用「一键种植」可批量播种背包中的种子。'"],
  ["return '作物需要每天浇水才会生长。「一键浇水」可一次浇完所有作物。'", "return i18n.global.locale.value === 'vi' ? 'Nông sản cần tưới nước mỗi ngày mới lớn. Dùng 「Tưới hàng loạt」 có thể tưới tất cả.' : '作物需要每天浇水才会生长。「一键浇水」可一次浇完所有作物。'"],
  ["return '金色高亮的地块表示作物已成熟，点击「一键收获」即可批量收获。'", "return i18n.global.locale.value === 'vi' ? 'Ô được tô sáng vàng báo hiệu nông sản đã chín, nhấp 「Thu hoạch hàng loạt」 để thu.' : '金色高亮的地块表示作物已成熟，点击「一键收获」即可批量收获。'"],
  ["getItemById(patch.oreId)?.name ?? '矿石'", "getItemById(patch.oreId)?.name ?? (i18n.global.locale.value === 'vi' ? 'Quặng' : '矿石')"],
  ["addLog(`收取了溪流鱼获：${names.join('、')}。`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã thu hoạch cá suối: ${names.join(', ')}.` : `收取了溪流鱼获：${names.join('、')}。`)"],
  ["addLog('背包已满，部分鱼获未能收取。')", "addLog(i18n.global.locale.value === 'vi' ? 'Balo đã đầy, một số cá chưa được thu.' : '背包已满，部分鱼获未能收取。')"],
  ["addLog('体力不足，无法开采。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không đủ thể lực, không thể khai thác.' : '体力不足，无法开采。')"],
  ["addLog('背包已满，无法开采。')", "addLog(i18n.global.locale.value === 'vi' ? 'Balo đã đầy, không thể khai thác.' : '背包已满，无法开采。')"],
  ["const oreName = getItemById(patch.oreId)?.name ?? '矿石'", "const oreName = getItemById(patch.oreId)?.name ?? (i18n.global.locale.value === 'vi' ? 'Quặng' : '矿石')"],
  ["addLog(`开采了地表矿脉，获得了${patch.quantity}个${oreName}。(+8挖矿经验)`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã khai thác mạch khoáng trên mặt đất, nhận được ${patch.quantity} ${oreName}. (+8 EXP đào)` : `开采了地表矿脉，获得了${patch.quantity}个${oreName}。(+8挖矿经验)`)"],
  ["return '万物铺' + getShopClosedReason(wanwupu, gameStore.day, gameStore.hour, gameStore.weather, gameStore.season)", "return (i18n.global.locale.value === 'vi' ? 'Tiệm Vạn Vật' : '万物铺') + getShopClosedReason(wanwupu, gameStore.day, gameStore.hour, gameStore.weather, gameStore.season)"],
  ["addLog(`将${name}×${quantity}放入了出货箱。`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã bỏ ${name}×${quantity} vào thùng hàng.` : `将${name}×${quantity}放入了出货箱。`)"],
  ["addLog(`从出货箱取出了${name}×${quantity}。`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã lấy ${name}×${quantity} ra khỏi thùng hàng.` : `从出货箱取出了${name}×${quantity}。`)"],
  ["name: '竹筒洒水器'", "name: i18n.global.locale.value === 'vi' ? 'Vòi phun tre' : '竹筒洒水器'"],
  ["name: '铜管洒水器'", "name: i18n.global.locale.value === 'vi' ? 'Vòi phun đồng' : '铜管洒水器'"],
  ["name: '金管洒水器'", "name: i18n.global.locale.value === 'vi' ? 'Vòi phun vàng' : '金管洒水器'"],
  ["label: '荒地'", "label: i18n.global.locale.value === 'vi' ? 'Đất hoang' : '荒地'"],
  ["label: '已耕'", "label: i18n.global.locale.value === 'vi' ? 'Đã cày' : '已耕'"],
  ["label: '已种'", "label: i18n.global.locale.value === 'vi' ? 'Đã trồng' : '已种'"],
  ["label: '生长中'", "label: i18n.global.locale.value === 'vi' ? 'Đang lớn' : '生长中'"],
  ["label: '已浇水'", "label: i18n.global.locale.value === 'vi' ? 'Đã tưới' : '已浇水'"],
  ["label: '可收获'", "label: i18n.global.locale.value === 'vi' ? 'Có thể thu' : '可收获'"],
  ["label: '巨型'", "label: i18n.global.locale.value === 'vi' ? 'Khổng lồ' : '巨型'"],
  ["label: '洒水器'", "label: i18n.global.locale.value === 'vi' ? 'Vòi phun' : '洒水器'"],
  ["label: '肥料'", "label: i18n.global.locale.value === 'vi' ? 'Phân bón' : '肥料'"],
  ["label: '需浇水'", "label: i18n.global.locale.value === 'vi' ? 'Cần tưới' : '需浇水'"],
  ["label: '虫害'", "label: i18n.global.locale.value === 'vi' ? 'Sâu bọ' : '虫害'"],
  ["label: '杂草'", "label: i18n.global.locale.value === 'vi' ? 'Cỏ dại' : '杂草'"],
  ["还有${unwateredCount.value}块需浇水", "${unwateredCount.value} ${i18n.global.locale.value==='vi'?'ô cần tưới nước':'块需浇水'}"],
  ["有${infestedCount.value}块虫害", "${infestedCount.value} ${i18n.global.locale.value==='vi'?'ô sâu bọ':'块虫害'}"],
  ["有${weedyCount.value}块杂草", "${weedyCount.value} ${i18n.global.locale.value==='vi'?'ô cỏ cỏ':'块杂草'}"],
  ["addLog('没有可种植的空耕地。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không có đất cày trống để trồng.' : '没有可种植的空耕地。')"],
  ["addLog(`一键种植了${planted}株育种种子（${getCropName(cropId)}）。(-${planted}体力)`)", "addLog(i18n.global.locale.value === 'vi' ? `Trồng nhanh ${planted} hạt giống lai (${getCropName(cropId)}). (-${planted} thể lực)` : `一键种植了${planted}株育种种子（${getCropName(cropId)}）。(-${planted}体力)`)"],
  ["addLog('体力不足，无法种植。')", "addLog(i18n.global.locale.value === 'vi' ? 'Cạn thể lực, không thể trồng.' : '体力不足，无法种植。')"],
  ["tip = '荒地（点击开垦）'", "tip = i18n.global.locale.value === 'vi' ? 'Đất hoang (Nhấn để khai khẩn)' : '荒地（点击开垦）'"],
  ["tip = '已耕地（点击播种）'", "tip = i18n.global.locale.value === 'vi' ? 'Đã cày (Nhấn để gieo)' : '已耕地（点击播种）'"],
  ["tip = `${crop?.name ?? ''}已成熟（点击收获）`", "tip = i18n.global.locale.value === 'vi' ? `${crop?.name ?? ''} đã chín (Nhấn để thu hoạch)` : `${crop?.name ?? ''}已成熟（点击收获）`"],
  ["tip = `${crop?.name ?? ''} ${plot.growthDays}/${effectiveDays}天 ${plot.watered ? '已浇水' : '需浇水'}`", "tip = i18n.global.locale.value === 'vi' ? `${crop?.name ?? ''} ${plot.growthDays}/${effectiveDays} ngày ${plot.watered ? 'Đã tưới' : 'Cần tưới'}` : `${crop?.name ?? ''} ${plot.growthDays}/${effectiveDays}天 ${plot.watered ? '已浇水' : '需浇水'}`"],
  ["tip += ' [洒水器]'", "tip += i18n.global.locale.value === 'vi' ? ' [Vòi phun]' : ' [洒水器]'"],
  ["tip += ` [虫害${plot.infestedDays}天]`", "tip += i18n.global.locale.value === 'vi' ? ` [Sâu bọ ${plot.infestedDays} ngày]` : ` [虫害${plot.infestedDays}天]`"],
  ["tip += ` [杂草${plot.weedyDays}天]`", "tip += i18n.global.locale.value === 'vi' ? ` [Cỏ dại ${plot.weedyDays} ngày]` : ` [杂草${plot.weedyDays}天]`"],
  ["addLog(`种下了育种种子：${getCropName(seed.genetics.cropId)} G${seed.genetics.generation}。`)", "addLog(i18n.global.locale.value === 'vi' ? `Gieo hạt giống lai: ${getCropName(seed.genetics.cropId)} G${seed.genetics.generation}.` : `种下了育种种子：${getCropName(seed.genetics.cropId)} G${seed.genetics.generation}。`)"],
  ["addLog(`收获了巨型${cropName}！获得了${result.quantity}个${cropName}！`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã thu hoạch ${cropName} khổng lồ! Nhận được ${result.quantity} ${cropName}!` : `收获了巨型${cropName}！获得了${result.quantity}个${cropName}！`)"],
  ["showFloat(`巨型${cropName} ×${result.quantity}`, 'accent')", "showFloat(i18n.global.locale.value === 'vi' ? `${cropName} khổng lồ ×${result.quantity}` : `巨型${cropName} ×${result.quantity}`, 'accent')"],
  ["addLog('没有该肥料了。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không còn phân bón này.' : '没有该肥料了。')"],
  ["addLog(`施了${fertDef?.name ?? '肥料'}。`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã bón ${fertDef?.name ?? 'phân'}.` : `施了${fertDef?.name ?? '肥料'}。`)"],
  ["addLog('无法在此施肥（需要已开垦且未施肥的地块）。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không thể bón phân ở đây (cần đất đã cày và chưa bón).' : '无法在此施肥（需要已开垦且未施肥的地块）。')"],
  ["addLog('没有该洒水器了。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không còn vòi phun này.' : '没有该洒水器了。')"],
  ["addLog('放置了洒水器，周围地块将自动浇水。')", "addLog(i18n.global.locale.value === 'vi' ? 'Đã đặt vòi phun, xung quanh ô sẽ được tưới tự động.' : '放置了洒水器，周围地块将自动浇水。')"],
  ["addLog('无法在此放置洒水器。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không thể đặt vòi phun ở đây.' : '无法在此放置洒水器。')"],
  ["addLog('拆除了洒水器，已回收到背包。')", "addLog(i18n.global.locale.value === 'vi' ? 'Đã gỡ vòi phun, thu hồi vào balo.' : '拆除了洒水器，已回收到背包。')"],
  ["addLog('背包已满，无法回收洒水器。')", "addLog(i18n.global.locale.value === 'vi' ? 'Balo đã đầy, không thể thu hồi vòi phun.' : '背包已满，无法回收洒水器。')"],
  ["addLog('背包中没有该树苗。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không có cây non này trong balo.' : '背包中没有该树苗。')"],
  ["addLog(`种下了${def.name}苗，需28天成熟。`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã trồng ${def.name} non, cần 28 ngày để lớn.` : `种下了${def.name}苗，需28天成熟。`)"],
  ["addLog(`果树位已满（最多${MAX_FRUIT_TREES}棵）。`)", "addLog(i18n.global.locale.value === 'vi' ? `Hết chỗ trồng cây ăn quả (Vượt quá ${MAX_FRUIT_TREES} cây).` : `果树位已满（最多${MAX_FRUIT_TREES}棵）。`)"],
  ["addLog('太晚了，没法砍伐了。')", "addLog(i18n.global.locale.value === 'vi' ? 'Muộn rồi, không chặt được.' : '太晚了，没法砍伐了。')"],
  ["addLog('斧头正在升级中，无法砍伐。')", "addLog(i18n.global.locale.value === 'vi' ? 'Rìu đang nâng cấp, không chặt được.' : '斧头正在升级中，无法砍伐。')"],
  ["addLog('体力不足，无法砍伐。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không đủ thể lực, không chặt được.' : '体力不足，无法砍伐。')"],
  ["addLog(`砍掉了${treeName}，获得${woodQty}个木材。（体力-${cost}）`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã gieo ${treeName}, nhận được ${woodQty} gỗ. (Thể lực-${cost})` : `砍掉了${treeName}，获得${woodQty}个木材。（体力-${cost}）`)"],
  ["addLog('背包中没有该种子。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không có hạt giống này trong balo.' : '背包中没有该种子。')"],
  ["addLog(`种下了${def.name}，需${def.growthDays}天成熟。`)", "addLog(i18n.global.locale.value === 'vi' ? `Trồng ${def.name}, cần ${def.growthDays} ngày để chín.` : `种下了${def.name}，需${def.growthDays}天成熟。`)"],
  ["addLog(`野树位已满（最多${MAX_WILD_TREES}棵）。`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã hết chỗ cho cây hoang dã (tối đa ${MAX_WILD_TREES}).` : `野树位已满（最多${MAX_WILD_TREES}棵）。`)"],
  ["addLog('背包中没有采脂器。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không có dụng cụ thu gom nhựa trong balo.' : '背包中没有采脂器。')"],
  ["addLog('安装了采脂器，将定期产出树脂。')", "addLog(i18n.global.locale.value === 'vi' ? 'Cài đặt thiết bị thu nhựa, tạo nhựa tự động.' : '安装了采脂器，将定期产出树脂。')"],
  ["addLog('无法安装采脂器（需要已成熟且未装采脂器的野树）。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không thể cài dụng cụ (yêu cầu cây trưởng thành không có dụng cụ).' : '无法安装采脂器（需要已成熟且未装采脂器的野树）。')"],
  ["addLog(`收取了${def?.tapProductName ?? productId}！`)", "addLog(i18n.global.locale.value === 'vi' ? `Thu được ${def?.tapProductName ?? productId}!` : `收取了${def?.tapProductName ?? productId}！`)"],
  ["addLog('太晚了，没法伐木了。')", "addLog(i18n.global.locale.value === 'vi' ? 'Đã trễ, không đốn củi được ráp.' : '太晚了，没法伐木了。')"],
  ["addLog('斧头正在升级中，无法伐木。')", "addLog(i18n.global.locale.value === 'vi' ? 'Rìu đang nâng cấp, không đốn được củi.' : '斧头正在升级中，无法伐木。')"],
  ["addLog('体力不足，无法伐木。')", "addLog(i18n.global.locale.value === 'vi' ? 'Cạn thể lực, không thể đốn củi.' : '体力不足，无法伐木。')"],
  ["addLog(`伐木获得了${qty}个木材，${treeName}已被砍倒消失了。（体力-${cost}）`)", "addLog(i18n.global.locale.value === 'vi' ? `Thu được ${qty} gỗ, ${treeName} đã bị đốn ngã. (Thể lực-${cost})` : `伐木获得了${qty}个木材，${treeName}已被砍倒消失了。（体力-${cost}）`)"],
  ["addLog(`伐木获得了${qty}个木材。（体力-${cost}）`)", "addLog(i18n.global.locale.value === 'vi' ? `Lấy được ${qty} gỗ. (Thể lực-${cost})` : `伐木获得了${qty}个木材。（体力-${cost}）`)"],
  ["addLog('背包中没有该种子了。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không có hạt giống này trong balo.' : '背包中没有该种子了。')"],
  ["addLog(`在温室中播种了${crop.name}。`)", "addLog(i18n.global.locale.value === 'vi' ? `Gieo hạt ${crop.name} ở nhà kính.` : `在温室中播种了${crop.name}。`)"],
  ["addLog('体力不足，无法收获。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không đủ thể lực để thu hoạch.' : '体力不足，无法收获。')"],
  ["let msg = `在温室收获了${cropDef?.name ?? cropId}${qtyLabel}${qualityLabel}！(-1体力)`", "let msg = (i18n.global.locale.value === 'vi') ? `Thu hoạch trong nhà kính ${cropDef?.name ?? cropId}${qtyLabel}${qualityLabel}! (-1 thể lực)` : `在温室收获了${cropDef?.name ?? cropId}${qtyLabel}${qualityLabel}！(-1体力)`"],
  ["if (yieldDouble) msg += ' 育种产量加成！'", "if (yieldDouble) msg += i18n.global.locale.value === 'vi' ? ' Thưởng năng suất nhai giống!' : ' 育种产量加成！'"],
  ["msg += ` 甜度加成+${bonusMoney}文`", "msg += i18n.global.locale.value === 'vi' ? ` Thưởng vị ngọt +${bonusMoney} xu` : ` 甜度加成+${bonusMoney}文`"],
  ["msg += ' 育种种子已回收。'", "msg += i18n.global.locale.value === 'vi' ? ' Hạt giống lai đã hồi phục.' : ' 育种种子已回收。'"],
  ["msg += ' 种子箱已满，育种种子丢失！'", "msg += i18n.global.locale.value === 'vi' ? ' Thùng hạt giống đã đầy, hạt giống lai mất!' : ' 种子箱已满，育种种子丢失！'"],
  ["showFloat(`温室收获 ×${harvested}`, 'success')", "showFloat(i18n.global.locale.value === 'vi' ? `Thu hoạch trong nhà kính ×${harvested}` : `温室收获 ×${harvested}`, 'success')"],
  ["let msg = `在温室一键收获了${harvested}株作物。(-${harvested}体力)`", "let msg = (i18n.global.locale.value === 'vi') ? `Thu hoạch nhanh ${harvested} cây trồng trong nhà kính. (-${harvested} thể lực)` : `在温室一键收获了${harvested}株作物。(-${harvested}体力)`"],
  ["addLog(`${seedsReturned}颗育种种子已回收到种子箱。`)", "addLog(i18n.global.locale.value === 'vi' ? `${seedsReturned} hạt giống lai đã trở lại thùng hạt giống.` : `${seedsReturned}颗育种种子已回收到种子箱。`)"],
  ["addLog(`在温室一键种植了${planted}株${crop.name}。(-${planted}体力)`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã trồng ${planted} cây ${crop.name} trong nhà kính. (-${planted} thể lực)` : `在温室一键种植了${planted}株${crop.name}。(-${planted}体力)`)"],
  ["addLog('体力不足或种子不够，无法种植。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không đủ thể lực hoặc không đủ hạt giống, không thể trồng.' : '体力不足或种子不够，无法种植。')"],
  ["addLog('材料不足，无法升级温室。')", "addLog(i18n.global.locale.value === 'vi' ? 'Thiếu nguyên liệu, không thể nâng cấp nhà kính.' : '材料不足，无法升级温室。')"],
  ["addLog('铜钱不足，无法升级温室。')", "addLog(i18n.global.locale.value === 'vi' ? 'Không đủ tiền đồng, không thể nâng cấp.' : '铜钱不足，无法升级温室。')"],
  ["addLog(`温室已升级至${upgrade.name}！（${upgrade.plotCount}个地块）`)", "addLog(i18n.global.locale.value === 'vi' ? `Nhà kính đã được nâng cấp lên ${upgrade.name}! (${upgrade.plotCount} ô đất)` : `温室已升级至${upgrade.name}！（${upgrade.plotCount}个地块）`)"],
  ["showFloat(`温室种植 ${crop.name} ×${planted}`, 'success')", "showFloat(i18n.global.locale.value === 'vi' ? `Trồng ${crop.name} ở nhà kính ×${planted}` : `温室种植 ${crop.name} ×${planted}`, 'success')"],
  ["addLog(`在温室种下了育种种子：${getCropName(seed.genetics.cropId)} G${seed.genetics.generation}。`)", "addLog(i18n.global.locale.value === 'vi' ? `Đã trồng trong nhà kính hạt giống lai: ${getCropName(seed.genetics.cropId)} G${seed.genetics.generation}。` : `在温室种下了育种种子：${getCropName(seed.genetics.cropId)} G${seed.genetics.generation}。`)"]
];

replacements.forEach(([search, replace]) => {
  content = content.replace(search, replace);
});

fs.writeFileSync('./taoyuan-main/src/views/game/FarmView.vue', content);
